import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/main/Header';
import { ThemeProvider } from '@/components/theme-provider';
import { DarkMode } from '@/components/Dark-mode';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex items-center justify-center gap-5'>
            <Header />
            <DarkMode />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
